export const statusLabels = {
  check: "Do sprawdzenia",
  missing: "Braki",
  decision: "Do decyzji",
  todo: "Do zrobienia",
  ready: "Bez zmian",
};

export const standardControlTasks = [
  "Sprawdzić stabilne podłączenie komputera do rzutnika, telewizora albo monitora multimedialnego.",
  "Zweryfikować, czy przewody są zamocowane na stałe i nie wiszą luźno.",
  "Sprawdzić, czy przewody nie są narażone na szarpanie, żeby nie wyłamywać złączy.",
  "Uruchomić zestaw i potwierdzić, że obraz wyświetla się poprawnie.",
];

const room = ({
  id,
  name,
  floor,
  location,
  purpose = "",
  teachers = [],
  status = "check",
  equipment = [],
  tasks = [],
  urgentTasks = [],
  notes = [],
  decisions = [],
}) => ({
  id,
  name,
  floor,
  location,
  purpose,
  teachers,
  status,
  equipment,
  tasks,
  urgentTasks,
  notes,
  decisions,
});

const group = (name, items) => ({ name, items });

export const rooms = [
  room({
    id: "2",
    name: "Sala 2",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Gabinet przedmiotów zawodowych fryzjerskich",
    teachers: ["Sylwia Mikołajczak", "Iwona Leniczowska", "Paweł Danielewski"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer stacjonarny", "Rzutnik"]),
    ],
    tasks: ["Sprawdzić prawidłowe podłączenie komputera do rzutnika", "Sprawdzić, czy obraz wyświetla się poprawnie"],
    decisions: ["Zostawić wyposażenie tak, jak jest"],
  }),
  room({
    id: "3",
    name: "Sala 3",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Przedmioty zawodowe fryzjerskie",
    teachers: ["Agnieszka Jastrzębska", "Paweł Danielewski", "Iwona Leniczowska", "Edyta Jaworska"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Telewizor multimedialny na kółkach, 75 cali"]),
    ],
    tasks: ["Zapewnić sprawne i stałe podłączenie komputera do telewizora", "Zamocować kabel tak, żeby nie latał i nie wisiał"],
  }),
  room({
    id: "4",
    name: "Sala 4",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Fryzjerstwo oraz edukacja obywatelska",
    teachers: ["Marcin Kruk", "Marcin Kopij"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Telewizor dotykowy na ścianie, 70 cali"]),
    ],
    tasks: ["Sprawdzić stałe podłączenie do telewizora", "Sprawdzić, czy telewizor dotykowy działa prawidłowo"],
  }),
  room({
    id: "5",
    name: "Sala 5",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Przedmioty zawodowe z zakresu fryzjerstwa i inne przedmioty",
    teachers: ["Beata Krzymińska", "Wojciech Biczysko", "Łukasz Wojciechowski", "Inni nauczyciele z pojedynczymi godzinami"],
    status: "missing",
    equipment: [
      group("Meble i wyposażenie specjalistyczne", ["Fotel barberski"]),
      group("Sprzęt komputerowy i multimedialny", ["Telewizor dotykowy Samsung, 75 cali", "Drukarka wielofunkcyjna A3"]),
      group("Docelowo", ["26 iPadów", "26 rysików", "Szafa zamykana na klucz z zasilaniem do ładowania iPadów"]),
    ],
    tasks: ["Sprawdzić telewizor dotykowy Samsung 75 cali", "Sprawdzić drukarkę wielofunkcyjną A3", "Dostarczyć 26 iPadów i 26 rysików", "Wziąć wszystkie zgromadzone iPady Air od Iwony Ochnik razem ze wszystkimi rysikami", "Przygotować do pracy iPady Air oraz dostępne tańsze iPady", "Zalogować iPady oraz ustawić uniwersalny PIN", "Zostawić iPady do używania razem z rysikami", "Przygotować szafę zamykaną na klucz", "Zapewnić w szafie miejsce na listwy i podłączenie do prądu, żeby tablety mogły ładować się na co dzień", "Dokładnie sprawdzić Wi-Fi", "Jeśli Wi-Fi jest za słabe, dodać access point"],
  }),
  room({
    id: "6",
    name: "Sala 6",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Połączona praktyczna pracownia fryzjerska z salą 7",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Rzutnik podwieszony pod sufitem"]),
    ],
    tasks: ["Sprawdzić pewne i sprawne podłączenie komputera do rzutnika"],
    notes: ["Sala 6 funkcjonalnie łączy się z salą 7"],
  }),
  room({
    id: "7",
    name: "Sala 7",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Część połączonej praktycznej pracowni fryzjerskiej z salą 6",
    notes: ["Traktować razem z salą 6 przy opisie pracowni praktycznej fryzjerskiej"],
  }),
  room({
    id: "8",
    name: "Sala 8",
    floor: "Parter",
    location: "Budynek główny / parter",
    purpose: "Gabinet, obecny układ zostaje",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Zamontowany rzutnik"]),
    ],
    tasks: ["Sprawdzić podłączenie komputera do rzutnika", "Sprawdzić, czy zestaw działa poprawnie"],
    decisions: ["Na razie zostawić obecny układ"],
  }),
  room({
    id: "04",
    name: "Sala 04",
    floor: "Piwnica",
    location: "Budynek główny / piwnica",
    status: "todo",
    equipment: [
      group("Obecne wyposażenie", ["Monitor wiszący w sali"]),
    ],
    tasks: ["Zabrać monitor z sali 04", "Ewentualnie kupić nóżki do monitora", "Przenieść monitor na wejście do szkoły jako monitor multimedialny dla uczniów", "Monitor przy wejściu ma służyć m.in. do wyszukiwania planu lekcji"],
  }),
  room({
    id: "05-new",
    name: "Nowa sala 05",
    floor: "Parter",
    location: "Budynek główny / parter / nowa sala wybudowana w szatni",
    purpose: "Sala językowa",
    teachers: ["Aleksandra Karczmarz", "Anna Galort"],
    status: "missing",
    equipment: [
      group("Do wstawienia / zakupu", ["Telewizor multimedialny na ścianę", "Być może komputer all-in-one", "Ławki", "Pełne wyposażenie sali lekcyjnej", "Biała tablica"]),
    ],
    urgentTasks: ["Kupić telewizor multimedialny na ścianę", "Kupić być może komputer all-in-one", "Kupić ławki", "Kupić / skompletować całe wyposażenie sali lekcyjnej", "Kupić / zamontować białą tablicę"],
    notes: ["Roboczo osobna nowa sala; trzeba później dopasować numerację do planu szkoły"],
  }),
  room({
    id: "16",
    name: "Pokój nauczycielski / Sala 16",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Pokój nauczycielski",
    equipment: [
      group("Sprzęt komputerowy", ["3 sprawne stanowiska komputerowe"]),
    ],
    tasks: ["Zapewnić 3 sprawne stanowiska komputerowe", "Każde stanowisko ma mieć internet", "Sprawdzić, czy działają drukarki", "Jeżeli drukarki nie działają, zdiagnozować usterki", "Zapewnić przynajmniej jedną sprawną, działającą i szybką drukarkę", "Do decyzji: jeśli obecne drukarki nie wystarczą, kupić sprawny kombajn"],
  }),
  room({
    id: "17",
    name: "Sala 17",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Matematyka, język niemiecki i inne przedmioty według planu",
    teachers: ["Marzena Filusz", "Małgorzata Fiodorow", "Inni nauczyciele z przedmiotami przelotnymi"],
    status: "missing",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Monitor multimedialny na kółkach, 75 cali"]),
      group("iPady", ["Docelowo 30 iPadów", "Szafka zamykana na klucz z zasilaniem do ładowania iPadów"]),
    ],
    tasks: ["Dostarczyć 30 iPadów", "Wstawić szafkę zamykaną na klucz", "Zapewnić w szafce zasilanie, żeby iPady mogły się ładować", "Sprawdzić internet na iPadach", "Sprawdzić Wi-Fi"],
  }),
  room({
    id: "18",
    name: "Sala 18",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Język polski i inne przedmioty według planu",
    teachers: ["Bożena Piątek-Pawłowska", "Ewentualnie Magdalena Zalewska", "Ewentualnie Waldemar Kaczorowski", "Ewentualnie Marcin Kopij"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Rzutnik na ścianie"]),
    ],
    tasks: ["Zostawić rzutnik", "Zadbać o stabilne połączenie rzutnika z komputerem", "Sprawdzić, czy zestaw działa"],
  }),
  room({
    id: "19",
    name: "Sala 19",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Zajęcia Magdaleny Zalewskiej i Waldemara Kaczorowskiego",
    teachers: ["Magdalena Zalewska", "Waldemar Kaczorowski", "Marcin Kopij"],
    status: "todo",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Monitor multimedialny z pracowni AI, aktualnie pod salą 36"]),
    ],
    tasks: ["Przynieść monitor multimedialny z pracowni AI, aktualnie spod sali 36", "Zamontować monitor", "Sprawdzić, czy monitor ma nóżki", "Podłączyć monitor do komputera"],
    notes: ["Sala 18 może być salą awaryjną dla tych zajęć"],
  }),
  room({
    id: "21",
    name: "Biblioteka / Czytelnia / Sala 21",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Biblioteka i czytelnia ze stanowiskami komputerowymi dla uczniów",
    status: "todo",
    equipment: [
      group("Sprzęt komputerowy", ["Laptopy dla uczniów zamiast komputerów stacjonarnych", "4-5 stanowisk komputerowych w czytelni"]),
      group("Bezpieczeństwo", ["Linki zabezpieczające", "Stałe podpięcie / zabezpieczenie laptopów"]),
    ],
    tasks: ["Wymienić komputery stacjonarne na laptopy dla uczniów", "Przygotować 4-5 stanowisk komputerowych", "Zadbać o linki zabezpieczające"],
  }),
  room({
    id: "22",
    name: "Sala 22",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Język polski i inne przedmioty według planu",
    teachers: ["Magdalena Ulanowska", "Inni nauczyciele z przedmiotami przelotnymi"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer stacjonarny", "Monitor multimedialny BenQ, 75 cali"]),
    ],
    tasks: ["Sprawdzić podłączenie komputera do monitora BenQ", "Sprawdzić, czy monitor 75 cali działa"],
    decisions: ["Na razie zostawić obecny układ"],
  }),
  room({
    id: "23",
    name: "Sala 23",
    floor: "I piętro",
    location: "Budynek główny / I piętro",
    purpose: "Przedmioty zawodowe",
    teachers: ["Eleonora Zmiernow-Zema", "Inni nauczyciele"],
    status: "decision",
    equipment: [
      group("Obecne wyposażenie", ["Stary rzutnik", "Drugi rzutnik do demontażu / potwierdzenia"]),
      group("Docelowo", ["30 laptopów w szafie z III piętra"]),
    ],
    tasks: ["Zdemontować stare rzutniki", "Wstawić do szafy 30 laptopów razem z szafą z III piętra"],
    notes: ["W rozmowie pojawiła się opcja monitora na kółkach, ale aktualny wariant to laptopy w szafie"],
  }),
  room({
    id: "26",
    name: "Sala 26",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Gabinet przyrodniczy",
    teachers: ["p. Małecka", "p. Sołdyka", "p. Mucha", "p. Chudziec"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer stacjonarny", "Telewizor 75 cali na ścianie"]),
    ],
    tasks: ["Sprawdzić podłączenie komputera do telewizora", "Zadbać o stabilne połączenie"],
    decisions: ["Zostawić wyposażenie tak, jak jest"],
  }),
  room({
    id: "27",
    name: "Sala 27",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Drugi gabinet przyrodniczy",
    teachers: ["p. Małecka", "p. Sołdyka", "p. Mucha", "p. Chudziec"],
    status: "missing",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Rzutnik"]),
      group("Tablety", ["30 tabletów, jeśli jest dostępna taka pula"]),
    ],
    tasks: ["Podłączyć rzutnik do komputera", "Sprawdzić, czy zestaw działa", "Potwierdzić dostępność 30 tabletów"],
  }),
  room({
    id: "28",
    name: "Sala 28",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Gabinet przyrodniczy / przedmioty przyrodnicze",
    teachers: ["p. Małecka", "p. Sołdyka", "p. Mucha", "p. Chudziec"],
    status: "decision",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Telewizor multimedialny", "Rzutnik / rzutniki do potwierdzenia"]),
    ],
    tasks: ["Zadbać, żeby telewizor multimedialny był w sali 28", "Sprawdzić połączenie komputera z telewizorem"],
    notes: ["Do potwierdzenia, co oznacza decyzja: zostawiamy tylko rzutniki"],
  }),
  room({
    id: "29",
    name: "Sala 29",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Gabinet matematyki",
    teachers: ["p. Bujanowska", "p. Ostrowska"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer stacjonarny", "Rzutnik"]),
    ],
    tasks: ["Sprawdzić stabilne połączenie rzutnika z komputerem", "Sprawdzić, czy zestaw działa"],
    decisions: ["Zostawić wyposażenie tak, jak jest"],
  }),
  room({
    id: "30",
    name: "Sala 30",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Język polski i inne przedmioty przechodnie",
    teachers: ["Anna Filipek", "Inni nauczyciele z przedmiotami przechodnimi"],
    status: "check",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Rzutnik"]),
    ],
    tasks: ["Zostawić rzutnik", "Sprawdzić, czy komputer jest podłączony do rzutnika"],
  }),
  room({
    id: "31",
    name: "Sala 31",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Gabinet przyrodniczy, geografia i inne przedmioty przyrodnicze",
    teachers: ["p. Smereka", "Inni nauczyciele z przedmiotami przechodnimi"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer stacjonarny", "Rzutnik"]),
    ],
    tasks: ["Podłączyć rzutnik do komputera stacjonarnego", "Sprawdzić, czy zestaw działa"],
  }),
  room({
    id: "32",
    name: "Sala 32",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Język angielski",
    teachers: ["p. Biezmienow", "Ewentualnie p. Karczmarz", "Ewentualnie p. Galort"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Rzutnik"]),
    ],
    tasks: ["Podłączyć rzutnik do komputera", "Sprawdzić, czy zestaw działa"],
  }),
  room({
    id: "33",
    name: "Sala 33",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Język polski i inne przedmioty przechodnie",
    teachers: ["Elina Krycia", "Inni nauczyciele z przedmiotami przechodnimi"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer", "Nowy telewizor"]),
    ],
    tasks: ["Zapewnić stabilne podłączenie komputera do nowego telewizora", "Sprawdzić, żeby obraz / system się nie zawieszał"],
  }),
  room({
    id: "34",
    name: "Sala 34",
    floor: "II piętro",
    location: "Budynek główny / II piętro",
    purpose: "Gabinet / przedmioty zawodowe i administracyjne według planu",
    teachers: ["Magdalena Nowak", "Arkadiusz Mocarski", "Małgorzata Kończyńska"],
    status: "decision",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Komputer stacjonarny", "Telewizor multimedialny"]),
    ],
    tasks: ["Podłączyć komputer stacjonarny do telewizora multimedialnego"],
    notes: ["Potwierdzić, że zamiast rzutnika jest telewizor multimedialny"],
  }),
  room({
    id: "37",
    name: "Sala 37",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    purpose: "Pracownia informatyczna / przedmioty zawodowe",
    teachers: ["Maciej Najwer", "Bożena Czukiewska", "Agnieszka Skarupa", "Anna Kosiń"],
    status: "missing",
    equipment: [
      group("Meble", ["24 ławki / stanowiska dla uczniów według osobnego szkicu"]),
      group("Sprzęt komputerowy", ["24 stanowiska dla uczniów", "25. komputer / stanowisko nauczyciela", "Wymiana stanowisk na laptopy", "Internet kablowy dla laptopów"]),
      group("Sprzęt dodatkowy", ["Drukarka A4", "Preferowany duplex"]),
    ],
    tasks: ["Przygotować 24 stanowiska uczniowskie według szkicu", "Przygotować stanowisko nauczyciela", "Zapewnić internet kablowy dla laptopów", "Dodać drukarkę A4, najlepiej z duplexem"],
  }),
  room({
    id: "38",
    name: "Sala 38",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    purpose: "Pracownia informatyczna / przedmioty zawodowe",
    teachers: ["Paweł Młynarczyk", "Magdalena Laszczycka"],
    status: "missing",
    equipment: [
      group("Meble", ["Układ w literę U", "6 luźnych ławek na środku"]),
      group("Sprzęt komputerowy", ["24 stanowiska dla uczniów", "25. stanowisko nauczyciela", "Nowy komputer nauczyciela zostaje", "Wymiana stanowisk na laptopy", "Internet kablowy dla laptopów"]),
    ],
    tasks: ["Zapewnić 24 stanowiska uczniowskie plus stanowisko nauczyciela", "Zapewnić internet kablowy dla laptopów"],
    decisions: ["Komputer nauczyciela zostaje", "Poza wymianą stanowisk na laptopy nie zmieniać układu"],
  }),
  room({
    id: "39",
    name: "Sala 39",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    purpose: "Sala gimnastyczna",
    notes: ["Na tym etapie bez dodatkowych zmian wyposażenia"],
  }),
  room({
    id: "40",
    name: "Sala 40",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Telewizor multimedialny", "Komputer"]),
    ],
    tasks: ["Zapewnić stabilne podłączenie telewizora multimedialnego do komputera", "Sprawdzić, czy zestaw działa"],
  }),
  room({
    id: "41",
    name: "Sala 41",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    purpose: "Pracownia handlowa / przedmioty zawodowe",
    status: "missing",
    equipment: [
      group("Sprzęt komputerowy", ["26 laptopów", "Szafa na laptopy jest już w sali"]),
      group("Sprzęt multimedialny", ["Nowy rzutnik, zostaje"]),
      group("Sieć", ["Przeciągnięty kabel do podłączenia"]),
    ],
    tasks: ["Wstawić 26 laptopów do istniejącej szafy", "Laptopy mają być wyczyszczone, nowe i działające", "Podłączyć laptopy do internetu", "Podłączyć przeciągnięty kabel sieciowy"],
    notes: ["Do potwierdzenia, czy obok rzutnika ma wejść duży niedotykowy telewizor z wcześniejszej notatki"],
  }),
  room({
    id: "42",
    name: "Sala 42",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    purpose: "Pracownia handlowa / przedmioty zawodowe",
    status: "missing",
    equipment: [
      group("Sprzęt komputerowy", ["26 laptopów", "Szafa na laptopy"]),
      group("Sprzęt multimedialny", ["Nowy rzutnik", "Nowy monitor multimedialny powieszony na ścianie"]),
    ],
    tasks: ["Zapewnić podłączenie monitora multimedialnego do komputera", "Wstawić 26 laptopów razem z szafą", "Laptopy mają być nowe i działające"],
  }),
  room({
    id: "43",
    name: "Sala 43",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Telewizor multimedialny", "Komputer"]),
    ],
    tasks: ["Zostawić telewizor multimedialny", "Zapewnić podłączenie telewizora do komputera", "Sprawdzić, czy wszystko działa"],
  }),
  room({
    id: "44",
    name: "Sala 44",
    floor: "III piętro",
    location: "Budynek główny / III piętro",
    status: "missing",
    teachers: ["Anna Misiąg", "Małgorzata Fiodorow"],
    equipment: [
      group("Sprzęt komputerowy i multimedialny", ["Monitor multimedialny / monitor", "Komputer"]),
      group("Tablety", ["20 tabletów, jeśli jeszcze się znajdą"]),
      group("Zasilanie", ["Zasilanie dla tabletów w sali"]),
    ],
    tasks: ["Zapewnić, żeby monitor był w sali", "Podłączyć komputer do monitora", "Wstawić tablety", "Przygotować zasilanie dla tabletów"],
    notes: ["Do potwierdzenia, czy docelowa liczba tabletów to 20"],
  }),
];

export const unresolvedItems = [
  "Rozróżnić salę 5 i nową roboczą salę 05 wybudowaną w szatni.",
  "Sala 23: potwierdzić finalny wariant po demontażu rzutników.",
  "Sale z iPadami: potwierdzić dostępność pełnych pul dla sali 5 i sali 17.",
  "Sale z Wi-Fi: po sprawdzeniu wskazać miejsca wymagające access pointów.",
  "Sala 28: potwierdzić, czy finalnie ma być telewizor multimedialny, rzutnik/rzutniki, czy oba typy sprzętu.",
  "Sala 34: potwierdzić, że komputer ma być podłączony do telewizora multimedialnego.",
  "Sala 37: dołączyć osobny szkic układu ławek.",
  "Sala 41: potwierdzić, czy oprócz nowego rzutnika ma być duży niedotykowy telewizor.",
  "Sala 44: potwierdzić, czy docelowa liczba tabletów to 20.",
];
